spring:
  application:
    name: security-service
  datasource:
    url: ${MYSQL_MEDICAL_SYSTEM}
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9000

logging:
  level:
    org.springframework.security: trace