spring:
  application:
    name: security-service
  datasource:
    url: ${MYSQL_MEDICAL_SYSTEM}
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9000

app:
  default-locale: ${APP_DEFAULT_LOCALE:vi}
  default-timezone: ${APP_DEFAULT_TIMEZONE:Asia/Ho_Chi_Minh}

logging:
  level:
    org.springframework.security: trace
    org.springframework.core.env: debug